name: "Docker QEMU Buildx ECR Action"
description: "Docker QEMU Buildx ECR Action - supports multi platform builds including linux/arm64 and ECR Push"
author: "bbharathkumarreddy@96@gmail.com"
branding:
  icon: "package"
  color: "blue"

inputs:
  platform:
    description: "Platform architecture to build."
    default: "linux/arm64"
    required: false
  ecr-push:
    description: "ECR push."
    default: "true"
    required: false
  aws-access-key-id:
    description: "AWS access key id."
    required: false
  aws-secret-access-key:
    description: "AWS Secret access key."
    required: false
  aws-region:
    description: "AWS region of the ECR repository."
    required: false
  ecr-repository:
    description: "ECR repository name."
    required: false
  ecr-tag:
    description: "AWS region."
    default: "latest"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      if: ${{ inputs.ecr-push == 'true' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      if: ${{ inputs.ecr-push == 'true' }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: ECR Build and push
      uses: docker/build-push-action@v5
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        IMAGE_TAG: ${{ inputs.ecr-tag }}
        AWS_REGION: ${{ inputs.aws-region }}
      with:
        push: ${{ inputs.ecr-push }}
        context: .
        platforms: ${{ inputs.platform }}
        tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        provenance: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
